### ISSUE TITLE
`icd -A` reports all files being downloaded despite some already local

### ISSUE THREAD

**Issue by danemacmillan** [farnots/iCloudDownloader#4]
I'll provide an example, and then illustrate with a screenshot.

Given a directory with six files, three of them are offloaded to iCloud, while the other three are already local. When running `icd -A`, it will report that all six files are being downloaded.

Note in the screenshot the three files with the `*.icloud` extension, and then note those files after the downloads have completed. Also note the three other files that have always been local.

<img width="727" alt="screen shot 2018-12-21 at 4 23 17 pm" src="https://user-images.githubusercontent.com/4390491/50364172-d585c080-053c-11e9-9b09-a6fad1895933.png">

**Comment by jfkassam** [comment]
This bug occurs because FileManager.isUbiquitousItem() simply states whether a file is "known" to iCloud (i.e. is either stored in iCloud or will be uploaded). It says nothing about whether it is present on the computer.

There is nothing in the FileManager API that allows a user of the API to differentiate between those two states, and therefore, to my knowledge, this bug is unsolvable.
